spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermanager
    username: root
    password: root@1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
grpc:
  port: 7016
  enableReflection: true
server:
  port: 8080
jwt:
  secret: "[B@7344699f"