// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.authenticationservice;

public interface AuthenticationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.authenticationservice.AuthenticationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jwtToken = 1;</code>
   * @return The jwtToken.
   */
  java.lang.String getJwtToken();
  /**
   * <code>string jwtToken = 1;</code>
   * @return The bytes for jwtToken.
   */
  com.google.protobuf.ByteString
      getJwtTokenBytes();
}
