// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.authenticationservice;

/**
 * Protobuf type {@code com.authenticationservice.AuthenticationResponse}
 */
public final class AuthenticationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.authenticationservice.AuthenticationResponse)
    AuthenticationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AuthenticationResponse.newBuilder() to construct.
  private AuthenticationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuthenticationResponse() {
    jwtToken_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AuthenticationResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.authenticationservice.Schema.internal_static_com_authenticationservice_AuthenticationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.authenticationservice.Schema.internal_static_com_authenticationservice_AuthenticationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.authenticationservice.AuthenticationResponse.class, com.authenticationservice.AuthenticationResponse.Builder.class);
  }

  public static final int JWTTOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object jwtToken_;
  /**
   * <code>string jwtToken = 1;</code>
   * @return The jwtToken.
   */
  @java.lang.Override
  public java.lang.String getJwtToken() {
    java.lang.Object ref = jwtToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jwtToken_ = s;
      return s;
    }
  }
  /**
   * <code>string jwtToken = 1;</code>
   * @return The bytes for jwtToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJwtTokenBytes() {
    java.lang.Object ref = jwtToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jwtToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jwtToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jwtToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jwtToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jwtToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.authenticationservice.AuthenticationResponse)) {
      return super.equals(obj);
    }
    com.authenticationservice.AuthenticationResponse other = (com.authenticationservice.AuthenticationResponse) obj;

    if (!getJwtToken()
        .equals(other.getJwtToken())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JWTTOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getJwtToken().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.authenticationservice.AuthenticationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.authenticationservice.AuthenticationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.authenticationservice.AuthenticationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.authenticationservice.AuthenticationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.authenticationservice.AuthenticationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.authenticationservice.AuthenticationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.authenticationservice.AuthenticationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.authenticationservice.AuthenticationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.authenticationservice.AuthenticationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.authenticationservice.AuthenticationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.authenticationservice.AuthenticationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.authenticationservice.AuthenticationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.authenticationservice.AuthenticationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.authenticationservice.AuthenticationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.authenticationservice.AuthenticationResponse)
      com.authenticationservice.AuthenticationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.authenticationservice.Schema.internal_static_com_authenticationservice_AuthenticationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.authenticationservice.Schema.internal_static_com_authenticationservice_AuthenticationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.authenticationservice.AuthenticationResponse.class, com.authenticationservice.AuthenticationResponse.Builder.class);
    }

    // Construct using com.authenticationservice.AuthenticationResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      jwtToken_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.authenticationservice.Schema.internal_static_com_authenticationservice_AuthenticationResponse_descriptor;
    }

    @java.lang.Override
    public com.authenticationservice.AuthenticationResponse getDefaultInstanceForType() {
      return com.authenticationservice.AuthenticationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.authenticationservice.AuthenticationResponse build() {
      com.authenticationservice.AuthenticationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.authenticationservice.AuthenticationResponse buildPartial() {
      com.authenticationservice.AuthenticationResponse result = new com.authenticationservice.AuthenticationResponse(this);
      result.jwtToken_ = jwtToken_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.authenticationservice.AuthenticationResponse) {
        return mergeFrom((com.authenticationservice.AuthenticationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.authenticationservice.AuthenticationResponse other) {
      if (other == com.authenticationservice.AuthenticationResponse.getDefaultInstance()) return this;
      if (!other.getJwtToken().isEmpty()) {
        jwtToken_ = other.jwtToken_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              jwtToken_ = input.readStringRequireUtf8();

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object jwtToken_ = "";
    /**
     * <code>string jwtToken = 1;</code>
     * @return The jwtToken.
     */
    public java.lang.String getJwtToken() {
      java.lang.Object ref = jwtToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jwtToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jwtToken = 1;</code>
     * @return The bytes for jwtToken.
     */
    public com.google.protobuf.ByteString
        getJwtTokenBytes() {
      java.lang.Object ref = jwtToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jwtToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jwtToken = 1;</code>
     * @param value The jwtToken to set.
     * @return This builder for chaining.
     */
    public Builder setJwtToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jwtToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jwtToken = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJwtToken() {
      
      jwtToken_ = getDefaultInstance().getJwtToken();
      onChanged();
      return this;
    }
    /**
     * <code>string jwtToken = 1;</code>
     * @param value The bytes for jwtToken to set.
     * @return This builder for chaining.
     */
    public Builder setJwtTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jwtToken_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.authenticationservice.AuthenticationResponse)
  }

  // @@protoc_insertion_point(class_scope:com.authenticationservice.AuthenticationResponse)
  private static final com.authenticationservice.AuthenticationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.authenticationservice.AuthenticationResponse();
  }

  public static com.authenticationservice.AuthenticationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthenticationResponse>
      PARSER = new com.google.protobuf.AbstractParser<AuthenticationResponse>() {
    @java.lang.Override
    public AuthenticationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuthenticationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthenticationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.authenticationservice.AuthenticationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

