// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.authenticationservice;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_authenticationservice_AuthenticationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_authenticationservice_AuthenticationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_authenticationservice_AuthenticationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_authenticationservice_AuthenticationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_authenticationservice_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_authenticationservice_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_authenticationservice_CreateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_authenticationservice_CreateUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\031com.authenticationservic" +
      "e\";\n\025AuthenticationRequest\022\020\n\010username\030\001" +
      " \001(\t\022\020\n\010password\030\002 \001(\t\"*\n\026Authentication" +
      "Response\022\020\n\010jwtToken\030\001 \001(\t\"7\n\021CreateUser" +
      "Request\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 " +
      "\001(\t\"&\n\022CreateUserResponse\022\020\n\010jwtToken\030\001 " +
      "\001(\t2\222\001\n\025AuthenticationService\022y\n\020authent" +
      "icateUser\0220.com.authenticationservice.Au" +
      "thenticationRequest\0321.com.authentication" +
      "service.AuthenticationResponse\"\0002\200\001\n\021Cre" +
      "ateUserService\022k\n\ncreateUser\022,.com.authe" +
      "nticationservice.CreateUserRequest\032-.com" +
      ".authenticationservice.CreateUserRespons" +
      "e\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_authenticationservice_AuthenticationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_authenticationservice_AuthenticationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_authenticationservice_AuthenticationRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_com_authenticationservice_AuthenticationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_authenticationservice_AuthenticationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_authenticationservice_AuthenticationResponse_descriptor,
        new java.lang.String[] { "JwtToken", });
    internal_static_com_authenticationservice_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_authenticationservice_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_authenticationservice_CreateUserRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_com_authenticationservice_CreateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_authenticationservice_CreateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_authenticationservice_CreateUserResponse_descriptor,
        new java.lang.String[] { "JwtToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
